# yum update
# yum install -y iproute
# yum install iputils
# yum install net-tools
# yum groupinstall "Development Tools"
# yum install gcc gcc-c++

# sudo ip tuntap add dev tun1 mode tun
# sudo ifconfig tun1 10.5.51.2/24 up

# ping -c 4 10.5.51.3


FROM fedora:29

LABEL Yiming Li <yli792@usc.edu>

RUN yum update -y

RUN yum install -y iproute \
               iputils \
               net-tools \ 
               gcc gcc-c++ \
               sudo

RUN yum groupinstall -y "Development Tools"

# RUN sudo ip tuntap add dev tun1 mode tun

# RUN sudo ifconfig tun1 10.5.51.2/24 up

CMD ["/bin/bash"]